---
title: "Figure1d_TregFACSstain"
author: Michael Rehli
output: 
  html_document:
    df_print: paged
    fig_caption: yes
    number_sections: no
    toc: yes
    toc_float: yes
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = normalizePath(".."))
knitr::write_bib(.packages(), "Figure1d_TregFACSstain.packages.bib")
```

## Bar charts showing the percentage of positive cells in allo and poly Treg expansion cultures

R packages

```{r, message=FALSE, warnings=FALSE}
library(tidyr)
library(ggplot2)
library(scales)
library(pzfx)
```

### data FoxP3

```{r}
stain.data <- read_pzfx("./data/Fig1_FoxP3_DataTable.xml")
rownames(stain.data) <- stain.data$ROWTITLE
data <- data.frame(t(as.matrix(stain.data[ ,2:11])))
data$type <-c(rep("allo",5), rep("poly",5))
# t-test
data.test <- t.test(FoxP3~type, data=data, var.equal = TRUE)
data.test
```


```{r, fig.width=2.5, fig.height=2.5}
p <- ggplot(data, aes(x=type, y=FoxP3, fill=type)) + coord_cartesian(ylim = c(0,115))
p <- p + stat_summary(fun = mean, geom = "bar", position = "dodge")
p <- p + geom_dotplot(binaxis='y', stackdir='center', position=position_dodge(.9), dotsize=5, stackratio = 1, binwidth=.75) 
p <- p + stat_summary(fun.data=mean_sdl, fun.args = list(mult=1), geom="errorbar", color="black", linewidth=0.5, width = 0.6, position = "dodge")
p <- p + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
p <- p + scale_fill_manual(values = c("darkorange2","steelblue"))
p <- p + labs(y="% of FoxP3+ cells among CD4+")
p <- p + scale_y_continuous(breaks = seq(0, 100, by = 20), expand=c(0,0))
p <- p + annotate("segment", x = 1, y = 105, xend = 2, yend = 105)
p <- p + annotate("text", x = 1.5, y = 110, label = "italic('n.s.')", size = 4, parse = TRUE)
p <- p + theme(axis.text=element_text(size=12))
p
pdf("./figures/FoxP3stain_percentPos.pdf", height=2.5, width=2.5)
p
dev.off()
```
### data Helios

```{r, fig.width=2.5, fig.height=2.5}
stain.data <- read_pzfx("./data/Fig1_Helios_DataTable.xml")
rownames(stain.data) <- stain.data$ROWTITLE
data <- data.frame(t(as.matrix(stain.data[ ,2:11])))
data$type <-c(rep("allo",5), rep("poly",5))
# t-test
data.test <- t.test(Helios~type, data=data, var.equal = TRUE)
data.test
```


```{r, fig.width=2.5, fig.height=2.5}
p <- ggplot(data, aes(x=type, y=Helios, fill=type)) + coord_cartesian(ylim = c(0,115))
p <- p + stat_summary(fun = mean, geom = "bar", position = "dodge")
p <- p + geom_dotplot(binaxis='y', stackdir='center', position=position_dodge(.9), dotsize=5, stackratio = 1, binwidth=.75) 
p <- p + stat_summary(fun.data=mean_sdl, fun.args = list(mult=1), geom="errorbar", color="black", linewidth=0.5, width = 0.6, position = "dodge")
p <- p + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
p <- p + scale_fill_manual(values = c("darkorange2","steelblue"))
p <- p + labs(y="% of Helios+ cells among CD4+")
p <- p + scale_y_continuous(breaks = seq(0, 100, by = 20), expand=c(0,0))
p <- p + annotate("segment", x = 1, y = 105, xend = 2, yend = 105)
p <- p + annotate("text", x = 1.5, y = 110, label = "italic('n.s.')", size = 4, parse = TRUE)
p <- p + theme(axis.text=element_text(size=12))
p
pdf("./figures/Heliosstain_percentPos.pdf", height=2.5, width=2.5)
p
dev.off()
```

### data Ki-67

```{r, fig.width=2.5, fig.height=2.5}
stain.data <- read_pzfx("./data/Fig1_Ki-67_DataTable.xml")
rownames(stain.data) <- "Ki67"
data <- data.frame(t(as.matrix(stain.data[ ,2:11])))
data$type <-c(rep("allo",5), rep("poly",5))
# t-test
data.test <- t.test(Ki67~type, data=data, var.equal = TRUE)
data.test
```


```{r, fig.width=2.5, fig.height=2.5}
p <- ggplot(data, aes(x=type, y=Ki67, fill=type)) + coord_cartesian(ylim = c(0,115))
p <- p + stat_summary(fun = mean, geom = "bar", position = "dodge")
p <- p + geom_dotplot(binaxis='y', stackdir='center', position=position_dodge(.9), dotsize=5, stackratio = 1, binwidth=.75) 
p <- p + stat_summary(fun.data=mean_sdl, fun.args = list(mult=1), geom="errorbar", color="black", linewidth=0.5, width = 0.6, position = "dodge")
p <- p + theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) 
p <- p + scale_fill_manual(values = c("darkorange2","steelblue"))
p <- p + labs(y="% of Ki-67+ cells among CD4+")
p <- p + scale_y_continuous(breaks = seq(0, 100, by = 20), expand=c(0,0))
p <- p + annotate("segment", x = 1, y = 85, xend = 2, yend = 85)
p <- p + annotate("text", x = 1.5, y = 90, label = "italic('n.s.')", size = 4, parse = TRUE)
p <- p + theme(axis.text=element_text(size=12))

p
pdf("./figures/Ki67stain_percentPos.pdf", height=2.5, width=2.5)
p
dev.off()
```

```{r}
sessionInfo(package = NULL)
writeLines(capture.output(sessionInfo(package = NULL)), "./Rscripts/Figure1d_TregFACSstain_SessionInfo.txt")
```



